version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: github-actions-orchestrator-test-db
    environment:
      POSTGRES_DB: github_actions_orchestrator_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"  # Use port 5433 to avoid conflicts with local PostgreSQL
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d github_actions_orchestrator_test"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - test-network

volumes:
  postgres_test_data:

networks:
  test-network:
    driver: bridge